version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./agentkit:/app/agentkit
      - ./main.py:/app/main.py
    environment:
      # Add any necessary environment variables here
      # EXAMPLE_VAR: example_value
      PYTHONUNBUFFERED: 1 # Ensures logs are shown in real-time
    depends_on:
      - mock_tool # Start mock_tool before api (doesn't guarantee readiness)

  mock_tool:
    build: . # Reuse the same build context (includes Flask via requirements.txt)
    working_dir: /app
    command: ["flask", "--app", "mock_tool:app", "run", "--host=0.0.0.0", "--port=9001"]
    volumes:
      - ./tests/mock_services/mock_tool.py:/app/mock_tool.py
    ports:
      - "9001:9001"
    environment:
      PYTHONUNBUFFERED: 1