# agentkit/core/interfaces/planner.py
from abc import ABC, abstractmethod
from typing import Any, Dict, List

from pydantic import BaseModel, Field


class PlanStep(BaseModel):
    """
    Represents a single step in an agent's plan.
    """

    action_type: str = Field(
        ..., description="The type of action to perform (e.g., 'tool_call', 'final_answer')."
    )
    details: Dict[str, Any] = Field(
        default_factory=dict,
        description="Arguments or specifics for the action (e.g., tool name and input).",
    )


class Plan(BaseModel):
    """
    Represents the overall plan generated by a planner.
    """

    steps: List[PlanStep] = Field(
        default_factory=list, description="The sequence of steps to execute."
    )


class BasePlanner(ABC):
    """
    Abstract base class for agent planning modules.

    Defines the standard interface for generating an execution plan based
    on a given goal or context.
    """

    @abstractmethod
    async def plan(self, goal: str, history: List[Dict[str, Any]]) -> Plan:
        """
        Generates an execution plan to achieve the given goal.

        Args:
            goal (str): The objective the agent needs to achieve.
            history (List[Dict[str, Any]]): The current memory or conversation history.

        Returns:
            Plan: The generated plan containing a sequence of steps.
        """
        raise NotImplementedError
